### ISSUE TITLE
buyer id error in action ts

### ISSUE THREAD

**Issue by sunseehray** [Wdd430-Team-7/Group_Project#50]
There's an error with the rating form. Please refer to screenshot:

![Image](https://github.com/Wdd430-Team-7/Group_Project/assets/93020746/76e975df-0813-4a07-842e-248488a6f0ed)

**Comment by mictlantecutli** [comment]
Thank you Sunshine, I hadn't checked the comments on github, this is new to me, but it seems like an amazing tool. Thanks, I will correct the error.

**Comment by sunseehray** [comment]
already fixed by Moises.
